artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/pritam1984314/NER-Pipelines/raw/main/ner_data.zip
  local_data_file: artifacts/data_ingestion/net_data
  unzip_dir: artifacts/data_ingestion
